[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements_deploy.txt"]

[start]
cmd = "uvicorn v4.api.main:app --host 0.0.0.0 --port $PORT --workers 1"
